# @Author: Zak Zhu
# @Date:   2021-02-22 13:25:03
# @Last Modified by:   Zak Zhu
# @Last Modified time: 2021-02-22 13:25:06
---
- name: "{{ playbook_dir | basename }}"
  hosts: localhost
  remote_user:
  gather_facts: yes
  vars:
    status: "{{ ansible_local[stats_file_name]['status'] | default('0') }}"
  force_handlers: no
  pre_tasks:
    - name: update ansible facts
      setup:
        gather_subset:
          - "all"

    - when: status == '0'
      block:
        - import_role:
            name: pre_roles/common
          tags:
            - pr_r_common
        - meta: flush_handlers

  tasks:
    # grub
    - when: status == '0'
      import_role:
        name: grub
      tags:
        - r_grub
    - meta: flush_handlers

    # network, security, ssh
    - when: status == '0'
      block:
        - import_role:
            name: net_names
          tags:
            - r_net_names
        - meta: flush_handlers

        - import_role:
            name: resolv
          tags:
            - r_resolv
        - meta: flush_handlers

        - import_role:
            name: security
          tags:
            - r_security
        - meta: flush_handlers

        - import_role:
            name: ssh_setup
          tags:
            - r_ssh_setup
        - meta: flush_handlers

    # preinstall
    - when: status == '0'
      block:
        - import_role:
            name: yum_repos
          tags:
            - r_yum_repos
        - meta: flush_handlers

        - import_role:
            name: yum_cron
          tags:
            - r_yum_cron
        - meta: flush_handlers

        - import_role:
            name: sys_preinst
          tags:
            - r_sys_preinst
        - meta: flush_handlers

    # common
    - when: status == '0'
      block:
        - import_role:
            name: alias_profile
          tags:
            - r_alias_profile
        - meta: flush_handlers

        - import_role:
            name: ascii_banner
          tags:
            - r_ascii_banner
        - meta: flush_handlers

        - import_role:
            name: base_kparams
          tags:
            - r_base_kparams
        - meta: flush_handlers

        - import_role:
            name: base_kparams_cron
          tags:
            - r_base_kparams_cron
        - meta: flush_handlers

        - import_role:
            name: base_rlimits
          tags:
            - base_rlimits
        - meta: flush_handlers

        - import_role:
            name: chrony
          tags:
            - r_chrony
        - meta: flush_handlers

        - import_role:
            name: history
          tags:
            - r_history
        - meta: flush_handlers

        - import_role:
            name: pip
          tags:
            - r_pip
        - meta: flush_handlers

        - import_role:
            name: prompt
          tags:
            - r_prompt
        - meta: flush_handlers

        # - import_role:
        #     name: sys_account
        #   tags:
        #     - r_sys_account
        # - meta: flush_handlers

        - import_role:
            name: vim
          tags:
            - r_vim
        - meta: flush_handlers

  post_tasks:
    - when: status == '0'
      block:
        - import_role:
            name: post_roles/common
          tags:
            - po_r_common
        - meta: flush_handlers
